Correct checkstyle fixes (except TODOs)
MetroCS/imagelab pull request #54
Opened 2020-11-12 20:59 UTC by cgamble2

* Closes issues #32, #33, #35 *

Fixed the formatting in ImgProvider.java and ImageLab.java to fit appropriate amount of characters per string

Slight formatting fix

Fixed all checkstyle issues on ImgProvider.java

Fixed checkstyle errors for three classes

added setter method to ILFrame class

Correct code convention violations in Run.java

* Fixed checkstyle issues with 'impro' variable in ImageLab.java

* Removed intellij files

* Fixed small issue with image provider variable not being set properly in ImgProvider.java

2020-11-12 22:38 UTC, jody reviewed
_File Changes_
M build.gradle (2)   **Why is `build.gradle` being changed as part of this PR?** 
A gf (462)      **Why is new file `gf` being added as part of this PR?**

2020-11-13 06:49 UTC, cgamble2 commented
Removed a stray space from `build.gradle` and deleted unnecessary `gf` file.

2020-11-14 01:34 UTC, jody commented
Was this closed in order to open a new (clean) PR?

2020-11-14 01:49 UTC, cgamble2 commented
Apologies, I had the wrong assumption about "close" when I published the comment.

2020-11-15 04:49 UTC, jody commented on Run.java
> +     * Default constructor - not used.
One you add an explicit constructor, Java no longer creates a "default constructor".
Perhaps a more appropriate comment would be "Disable the default constructor for this utility class."

2020-11-15 04:49 UTC, jody commented on Run.java
> +     *             application
This comment isn't particularly useful.  It should answer the question, "What are the command-line arguments to ImageLab?"

2020-11-15 04:55 UTC, jody commented on imagelab/DisplayImage.java
> -
What is the rationale for removing this whitespace?
Looking at this block of code, it seems like more (rather than less) whitespace might be useful.

2020-11-15 18:56 UTC, jody requested changes
As I try to review this, I'm finding the PR too broad and encompasses a breadth of change types, from simple formatting to significant refactoring and associated design decision making.

The original issue (#32), identified as an epic, doesn't appropriately reflect the complexity of the objective.  Although there is a single tool that is identifying shortcomings in the source code, Checkstyle, the reported "errors" are not all of the same type, do not require the same degree of design choice, nor do they have the same level of impact on the maintainability of the product.

**This PR needs to be broken into smaller _unit_ PRs**.  

The sub-issues (#33, #34, #35) likewise may each need to be broken down into smaller sub-issues to enable meaningful corrections in shorter time cycles.

I'm leaving in the few comments I'd made already, but they by no means constitute a full review.

Will set this PR to DRAFT with the expectation that it will be CLOSED after further discussion and potential reorganization of the User Stories.

2020-11-19 20:38 UTC, cgamble2 commented
Closing this PR to submit a chain of PR's that contain fixes to smaller, individual issues by type and/or class.

2020-11-19 20:38 UTC, closed without merging

2020-11-19 20:39 UTC, jody commented
@cgamble2 Please close this PR so that it no longer shows up as active.
Looking forward to the new issues and PRs.